<a href="https://colab.research.google.com/github/saihaneesh26/COLAB-Notebooks/blob/main/hackerearth_predict_the_power.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#highest accuracy is obtained using RandomForestClassifier - 95.01% - n_estimators=100
#DecisionTree - 93%
#SVM -  60%
#other  approx 30-50%
#Rank in contest - 135
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
main_db = pd.read_csv('/content/train.csv')
main_db

tracking_id  ... windmill_generated_power(kW/h)
0       WM_33725  ...                       6.766521
1         WM_698  ...                       5.966275
2       WM_39146  ...                       2.874342
3        WM_6757  ...                      14.851089
4       WM_21521  ...                       3.519074
...          ...  ...                            ...
3031      WM_343  ...                       5.864100
3032    WM_11599  ...                      20.127939
3033    WM_36921  ...                       2.264522
3034     WM_1067  ...                       3.016352
3035      WM_994  ...                       1.581180

[3036 rows x 22 columns]

In [4]:
main_db.columns

Index(['tracking_id', 'datetime', 'wind_speed(m/s)',
       'atmospheric_temperature(°C)', 'shaft_temperature(°C)',
       'blades_angle(°)', 'gearbox_temperature(°C)', 'engine_temperature(°C)',
       'motor_torque(N-m)', 'generator_temperature(°C)',
       'atmospheric_pressure(Pascal)', 'area_temperature(°C)',
       'windmill_body_temperature(°C)', 'wind_direction(°)', 'resistance(ohm)',
       'rotor_torque(N-m)', 'turbine_status', 'cloud_level', 'blade_length(m)',
       'blade_breadth(m)', 'windmill_height(m)',
       'windmill_generated_power(kW/h)'],
      dtype='object')

In [5]:
main_db = main_db.dropna(subset=["tracking_id","datetime"])

In [6]:
main_db1 = main_db.fillna(main_db.mean())

In [7]:
mode1 = main_db["cloud_level"].mode()
mode2=main_db["turbine_status"].mode()
main_db1["cloud_level"].fillna("Low",inplace=True)
main_db1["turbine_status"].fillna("BB",inplace=True)

In [8]:
db1 = pd.get_dummies(main_db1,columns = ["cloud_level","turbine_status"])
tid=np.array(db1["tracking_id"])
dt = np.array(db1["datetime"])
Y_DB = np.array(db1["windmill_generated_power(kW/h)"])
Y_DB = Y_DB.reshape(-1,1)
s = StandardScaler()
s.fit_transform(Y_DB)

array([[ 0.25530541],
       [-0.04122409],
       [-1.18693361],
       ...,
       [-1.41290113],
       [-1.1343119 ],
       [-1.66611222]])

In [9]:
db2 = db1.drop(columns=['tracking_id',"datetime"])
print(str(db2.isnull().sum()))

wind_speed(m/s)                   0
atmospheric_temperature(°C)       0
shaft_temperature(°C)             0
blades_angle(°)                   0
gearbox_temperature(°C)           0
engine_temperature(°C)            0
motor_torque(N-m)                 0
generator_temperature(°C)         0
atmospheric_pressure(Pascal)      0
area_temperature(°C)              0
windmill_body_temperature(°C)     0
wind_direction(°)                 0
resistance(ohm)                   0
rotor_torque(N-m)                 0
blade_length(m)                   0
blade_breadth(m)                  0
windmill_height(m)                0
windmill_generated_power(kW/h)    0
cloud_level_Extremely Low         0
cloud_level_Low                   0
cloud_level_Medium                0
turbine_status_A                  0
turbine_status_A2                 0
turbine_status_AAA                0
turbine_status_AB                 0
turbine_status_ABC                0
turbine_status_AC                 0
turbine_status_B            

In [10]:
# minval=db2.min()
# maxval = db2.max()

# db2 -=db2.min()
# db2 /=db2.max()

scaler = StandardScaler()

scaled_features =  scaler.fit_transform(db2.values)
db2 =pd.DataFrame(scaled_features,index = db2.index,columns=db2.columns)
db2

wind_speed(m/s)  ...  turbine_status_D
0            0.341050  ...         -0.269799
1            2.267890  ...         -0.269799
2            0.349762  ...         -0.269799
3            2.228395  ...         -0.269799
4           -0.761178  ...         -0.269799
...               ...  ...               ...
3031        -2.186812  ...         -0.269799
3032        -1.589179  ...         -0.269799
3033         0.334041  ...         -0.269799
3034         0.361215  ...         -0.269799
3035         0.393084  ...         -0.269799

[3036 rows x 35 columns]

In [11]:
db2["tracking_id"]=tid
db2["datetime"]=dt
print(str(db2.isnull().sum()))

wind_speed(m/s)                   0
atmospheric_temperature(°C)       0
shaft_temperature(°C)             0
blades_angle(°)                   0
gearbox_temperature(°C)           0
engine_temperature(°C)            0
motor_torque(N-m)                 0
generator_temperature(°C)         0
atmospheric_pressure(Pascal)      0
area_temperature(°C)              0
windmill_body_temperature(°C)     0
wind_direction(°)                 0
resistance(ohm)                   0
rotor_torque(N-m)                 0
blade_length(m)                   0
blade_breadth(m)                  0
windmill_height(m)                0
windmill_generated_power(kW/h)    0
cloud_level_Extremely Low         0
cloud_level_Low                   0
cloud_level_Medium                0
turbine_status_A                  0
turbine_status_A2                 0
turbine_status_AAA                0
turbine_status_AB                 0
turbine_status_ABC                0
turbine_status_AC                 0
turbine_status_B            

In [12]:
Y = pd.DataFrame(db2["windmill_generated_power(kW/h)"])
X = db2.drop(["windmill_generated_power(kW/h)","tracking_id","datetime"],axis=1)
X = X.drop(columns=['blade_length(m)','wind_direction(°)','atmospheric_pressure(Pascal)','atmospheric_temperature(°C)'])

In [13]:
x_train,x_test,y_train,y_test = train_test_split(X,Y)
X

wind_speed(m/s)  ...  turbine_status_D
0            0.341050  ...         -0.269799
1            2.267890  ...         -0.269799
2            0.349762  ...         -0.269799
3            2.228395  ...         -0.269799
4           -0.761178  ...         -0.269799
...               ...  ...               ...
3031        -2.186812  ...         -0.269799
3032        -1.589179  ...         -0.269799
3033         0.334041  ...         -0.269799
3034         0.361215  ...         -0.269799
3035         0.393084  ...         -0.269799

[3036 rows x 30 columns]

In [14]:
print(x_train.shape)
print(x_test.shape)

(2277, 30)
(759, 30)


In [65]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 1,max_features=29)
regressor.fit(x_train,y_train)  

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features=29, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=1000, n_jobs=10, oob_score=False,
                      random_state=1, verbose=0, warm_start=False)

In [66]:
regressor.score(x_test,y_test)

0.9274895534432084

In [27]:
testdb = pd.read_csv('/content/test.csv')
#main_db = main_db.dropna(subset=["tracking_id","datetime"])
testdb

tracking_id             datetime  ...  blade_breadth(m)  windmill_height(m)
0        WM_19817  2019-04-17 08:53:20  ...          0.403965           25.572431
1        WM_18723  2019-03-30 07:43:20  ...          0.444755           24.371823
2        WM_34552  2019-08-10 11:33:20  ...          0.387368           27.654677
3        WM_28570  2019-06-26 03:53:20  ...          0.450478           24.189426
4        WM_36934  2019-08-27 16:43:20  ...          0.368355            4.885440
...           ...                  ...  ...               ...                 ...
12081    WM_13376  2019-02-12 11:33:20  ...          0.407771           20.888674
12082     WM_1630  2018-11-12 17:33:20  ...          0.367823           24.793606
12083    WM_24703  2019-05-27 11:53:20  ...          0.459887            5.653451
12084    WM_22893  2019-05-13 21:53:20  ...          0.394680           24.591364
12085    WM_14513  2019-02-20 23:43:20  ...          0.490893           21.665001

[12086 rows x 21 columns]

In [28]:
testdb = testdb.dropna(subset=["tracking_id","datetime"])
testdb = testdb.drop(columns=['wind_direction(°)','blade_length(m)','atmospheric_pressure(Pascal)','atmospheric_temperature(°C)'])

In [29]:
print(str(testdb.isnull().sum()))

tracking_id                        0
datetime                           0
wind_speed(m/s)                  126
shaft_temperature(°C)              1
blades_angle(°)                  106
gearbox_temperature(°C)            1
engine_temperature(°C)             5
motor_torque(N-m)                 11
generator_temperature(°C)          5
area_temperature(°C)               1
windmill_body_temperature(°C)    926
resistance(ohm)                    0
rotor_torque(N-m)                281
turbine_status                   797
cloud_level                      125
blade_breadth(m)                   0
windmill_height(m)               255
dtype: int64


In [30]:
print(testdb["cloud_level"].mode())
print(testdb["turbine_status"].mode())
testdb["cloud_level"].fillna("Low",inplace=True)
testdb["turbine_status"].fillna("BB",inplace=True)
testdb = testdb.fillna(testdb.mean())

0    Low
dtype: object
0    BB
dtype: object


In [31]:
l = []
tid=np.array(testdb["tracking_id"])
dt = np.array(testdb["datetime"])
ndb = testdb.drop(columns=["tracking_id",'datetime'])
ndb1 = pd.get_dummies(ndb,columns = ["cloud_level","turbine_status"])
ndb1 = scaler.fit_transform(ndb1)
ndb1

array([[ 0.32940966,  1.83598231,  1.27451617, ..., -0.26819591,
        -0.263917  , -0.2637376 ],
       [-0.78307142,  0.12305416,  1.17675285, ..., -0.26819591,
        -0.263917  , -0.2637376 ],
       [ 3.66845927,  0.04204996,  0.76325146, ..., -0.26819591,
        -0.263917  , -0.2637376 ],
       ...,
       [-0.70253713,  0.12228569,  0.18004274, ..., -0.26819591,
        -0.263917  , -0.2637376 ],
       [ 0.31527529,  0.14403884,  0.16988964, ..., -0.26819591,
        -0.263917  , -0.2637376 ],
       [-0.35360417,  0.13073095,  0.39010554, ..., -0.26819591,
        -0.263917  , -0.2637376 ]])

In [32]:
regressor.predict(ndb1)

array([-1.32917701, -1.3276574 , -0.9296969 , ..., -0.22920311,
       -0.2544258 ,  1.46465498])

In [33]:
finaldb = pd.DataFrame()
finaldb["tracking_id"]=tid
finaldb["datetime"]=dt

finaldb["windmill_generated_power(kW/h)"]=regressor.predict(ndb1)
finaldb

tracking_id             datetime  windmill_generated_power(kW/h)
0        WM_19817  2019-04-17 08:53:20                       -1.329177
1        WM_18723  2019-03-30 07:43:20                       -1.327657
2        WM_34552  2019-08-10 11:33:20                       -0.929697
3        WM_28570  2019-06-26 03:53:20                       -0.866697
4        WM_36934  2019-08-27 16:43:20                       -1.017101
...           ...                  ...                             ...
12081    WM_13376  2019-02-12 11:33:20                        0.198149
12082     WM_1630  2018-11-12 17:33:20                       -0.993642
12083    WM_24703  2019-05-27 11:53:20                       -0.229203
12084    WM_22893  2019-05-13 21:53:20                       -0.254426
12085    WM_14513  2019-02-20 23:43:20                        1.464655

[12086 rows x 3 columns]

In [34]:
#finaldb["windmill_generated_power(kW/h)"] = finaldb["windmill_generated_power(kW/h)"]
l = pd.DataFrame(finaldb)
l_data = s.inverse_transform(finaldb["windmill_generated_power(kW/h)"])
l_data
finaldb["windmill_generated_power(kW/h)"]=np.array(l_data)
finaldb

tracking_id             datetime  windmill_generated_power(kW/h)
0        WM_19817  2019-04-17 08:53:20                        2.490469
1        WM_18723  2019-03-30 07:43:20                        2.494570
2        WM_34552  2019-08-10 11:33:20                        3.568548
3        WM_28570  2019-06-26 03:53:20                        3.738566
4        WM_36934  2019-08-27 16:43:20                        3.332671
...           ...                  ...                             ...
12081    WM_13376  2019-02-12 11:33:20                        6.612273
12082     WM_1630  2018-11-12 17:33:20                        3.395979
12083    WM_24703  2019-05-27 11:53:20                        5.458975
12084    WM_22893  2019-05-13 21:53:20                        5.390906
12085    WM_14513  2019-02-20 23:43:20                       10.030199

[12086 rows x 3 columns]

In [35]:
finaldb.to_csv("s3.csv")

In [220]:
from sklearn.tree import DecisionTreeRegressor
clf = DecisionTreeRegressor(random_state=1,criterion='mse',max_features=25) 

In [221]:
clf.fit(X.astype("float"),Y.astype("float"))

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=25, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

In [222]:
clf.score(x_train.astype("float"),y_train.astype("float"))

0.9999999986585956

In [223]:
l = clf.predict(ndb1)

In [224]:
l

array([-1.19940821, -1.2461163 , -0.83269924, ..., -0.31816373,
       -0.21570704,  1.71722349])

In [225]:
finaldb_dt = pd.DataFrame()
finaldb_dt["tracking_id"]=tid
finaldb_dt["datetime"]=dt

finaldb_dt["windmill_generated_power(kW/h)"]=l
finaldb_dt

tracking_id             datetime  windmill_generated_power(kW/h)
0        WM_19817  2019-04-17 08:53:20                       -1.199408
1        WM_18723  2019-03-30 07:43:20                       -1.246116
2        WM_34552  2019-08-10 11:33:20                       -0.832699
3        WM_28570  2019-06-26 03:53:20                        0.316164
4        WM_36934  2019-08-27 16:43:20                       -0.916822
...           ...                  ...                             ...
12081    WM_13376  2019-02-12 11:33:20                        0.307235
12082     WM_1630  2018-11-12 17:33:20                       -0.654420
12083    WM_24703  2019-05-27 11:53:20                       -0.318164
12084    WM_22893  2019-05-13 21:53:20                       -0.215707
12085    WM_14513  2019-02-20 23:43:20                        1.717223

[12086 rows x 3 columns]

In [226]:
dt = pd.DataFrame(finaldb_dt)
l_data = s.inverse_transform(finaldb_dt["windmill_generated_power(kW/h)"])
l_data
finaldb_dt["windmill_generated_power(kW/h)"]=np.array(l_data)
finaldb_dt

tracking_id             datetime  windmill_generated_power(kW/h)
0        WM_19817  2019-04-17 08:53:20                        2.907055
1        WM_18723  2019-03-30 07:43:20                        2.781525
2        WM_34552  2019-08-10 11:33:20                        3.892605
3        WM_28570  2019-06-26 03:53:20                        6.980237
4        WM_36934  2019-08-27 16:43:20                        3.666520
...           ...                  ...                             ...
12081    WM_13376  2019-02-12 11:33:20                        6.956239
12082     WM_1630  2018-11-12 17:33:20                        4.371740
12083    WM_24703  2019-05-27 11:53:20                        5.275447
12084    WM_22893  2019-05-13 21:53:20                        5.550805
12085    WM_14513  2019-02-20 23:43:20                       10.745660

[12086 rows x 3 columns]

In [227]:
finaldb_dt.to_csv("s2.csv")

In [68]:
#SVM
from sklearn import svm

In [77]:
svmclf = svm.SVR(kernel='rbf',C=10,degree=6)
svmclf.fit(x_train,y_train)
svmclf.score(x_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5941627544201898

In [76]:
from sklearn.neighbors import KNeighborsRegressor
model_kn = KNeighborsRegressor()
model_kn.fit(x_train,y_train)
model_kn.score(x_test,y_test)

0.32121638795984

In [58]:
from sklearn.linear_model import LassoCV
model_lv = LassoCV()
model_lv.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1088: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
        max_iter=1000, n_alphas=100, n_jobs=None, normalize=False,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [59]:
model_lv.score(x_test,y_test)

0.3735789344674451

In [60]:
from sklearn.linear_model import RidgeCV
model_r = RidgeCV()
model_r.fit(x_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=None, fit_intercept=True,
        gcv_mode=None, normalize=False, scoring=None, store_cv_values=False)

In [61]:
model_r.score(x_test,y_test)

0.37162346692721615

In [62]:
from sklearn.linear_model import ElasticNetCV
model_ev = ElasticNetCV()
model_ev.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1088: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ElasticNetCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
             l1_ratio=0.5, max_iter=1000, n_alphas=100, n_jobs=None,
             normalize=False, positive=False, precompute='auto',
             random_state=None, selection='cyclic', tol=0.0001, verbose=0)

In [63]:
model_ev.score(x_test,y_test)

0.37222362707207796

In [64]:
from sklearn.naive_bayes import GaussianNB
model_gnb = GaussianNB()
model_gnb.fit(x_train.astype("int"),y_train.astype("int"))
model_gnb.score(x_test.astype("int"),y_test.astype("int"))

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.26745718050065875